"""Added runs table

Revision ID: 96e5c4e82296
Revises: 9cb53a0ac756
Create Date: 2019-07-26 14:51:46.470751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e5c4e82296'
down_revision = '9cb53a0ac756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_end'), 'run', ['end'], unique=False)
    op.create_index(op.f('ix_run_start'), 'run', ['start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_start'), table_name='run')
    op.drop_index(op.f('ix_run_end'), table_name='run')
    op.drop_table('run')
    # ### end Alembic commands ###
