"""Added distance field to Run

Revision ID: bc0802e02a8d
Revises: 96e5c4e82296
Create Date: 2019-07-26 14:55:39.134330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0802e02a8d'
down_revision = '96e5c4e82296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('distance', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_run_distance'), 'run', ['distance'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_distance'), table_name='run')
    op.drop_column('run', 'distance')
    # ### end Alembic commands ###
